# Generated by Django 6.0 on 2026-01-27 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0027_alter_datospersonales_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimientos',
            name='reconocimientodelacolumnadearriba',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado_IMG'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='reconocimiento_PDFIMG'),
        ),
    ]
